#!/bin/bash

# get filename


## vvvvvvvvvvvvvvvv  Either set 'path' to install location, or read it from file 
export path=$(cat $HOME/.config/protograph)
## ^^^^^^^^^^^^^^^^

# accept 'ls' subcommand to check what graphs exist
if test "$1" == "ls"; then
    ls $path/data | grep -v "_bak$"
    exit
fi

# accept graph name as argument
if test -z $1; then
    # default
    export file=$path/data/test
else
    export file=$path/data/$1
    shift
fi

echo "using $file"

if test "$1" == "render"; then
    echo "rendering"
    $path/protograph.sh $@
    exit
fi

while true; do
    read -p "> " command

    if test "$command" == "q"; then
	exit
    fi

    $path/protograph.sh $command

done
