#!/bin/bash

# get filename


## vvvvvvvvvvvvvvvv  Either set 'path' to install location, or read it from file 
export path=$(cat $HOME/.config/protograph)
## ^^^^^^^^^^^^^^^^

if ! test -e $path/data; then
    mkdir $path/data
fi

# accept 'ls' subcommand to check what graphs exist
if test "$1" == "ls"; then
    ls $path/data | grep -v "_bak$"
    exit
fi

# accept '-f' flag to read commands from a file
if test "$1" == "-f"; then
    export in_file=$2
    # set and clear reusable data file
    export file=$path/data/.from_file
    > $file
# accept graph name as argument
elif test -z $1; then
    # default
    export file=$path/data/test
else
    export file=$path/data/$1
    shift
fi

echo "using $file"

if test "$1" == "render"; then
    echo "rendering"
    $path/protograph.sh $@
    exit
fi

# enter interactive mode if no file specified
if test -z $in_file; then
    while true; do
        read -p "> " command

        if test "$command" == "q"; then
        exit
        fi

        $path/protograph.sh $command

    done
# otherwise execute file line by line
else
    while IFS= read -r command; do
        $path/protograph.sh $command
    done < $in_file
fi
