#!/bin/bash

# get filename


## vvvvvvvvvvvvvvvv  Either set 'path' to install location, or read it from file 
export path=$(cat $HOME/.config/protograph)
## ^^^^^^^^^^^^^^^^


# accept graph name as argument
if test -z $1; then
    # default
    export file=$path/data/test
else
    export file=$path/data/$1
fi

echo "using $file"

while true; do
    read -p "> " command

    if test "$command" == "q"; then
	exit
    fi

    $path/protograph $command

done
